# -*- coding: utf-8 -*-
"""СДИА Покупательная способность товара

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PPnWUY7mdbrDxSZThCezVlIZlTJtFP2

# Прогноз суммы покупки с помощью полносвязной нейросети (FCN)

В этой работе берём датасет *shopping_trends.csv* и строим модель регрессии, которая предсказывает сумму покупки клиента.  
Используем полносвязную нейросеть в TensorFlow/Keras и показываем две кривые обучения: MAE и MSE (loss) для train и validation.
"""

# Импорты и общие настройки
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, callbacks, regularizers

import warnings
warnings.filterwarnings("ignore")

RANDOM_STATE = 42
EPOCHS = 200
BATCH_SIZE = 32

tf.keras.utils.set_random_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

"""## Шаг 1. Загрузка данных

Здесь загружаем CSV‑файл с данными о покупках и смотрим первые строки таблицы.

"""

from google.colab import files
print("📂 Загрузите shopping_trends.csv")
uploaded = files.upload()

fname = list(uploaded.keys())[0]
df = pd.read_csv(fname)

print("✅ Загружено:", fname, "| shape:", df.shape)
df.head()

"""## Шаг 2. Выбор целевой переменной и признаков

- В качестве целевой переменной берём столбец **Purchase Amount (USD)**.  
- Остальные столбцы используем как признаки, кроме **Customer ID** (ID не несёт полезной информации).

"""

# Target (регрессия)
target_col = "Purchase Amount (USD)"
y = df[target_col].astype(np.float32).values

# Признаки: убираем ID и target
X_df = df.drop(columns=["Customer ID", target_col], errors="ignore")

cat_cols = X_df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
num_cols = X_df.select_dtypes(include=[np.number]).columns.tolist()

print("\n✅ Признаки:", X_df.shape[1])
print("Категориальных:", len(cat_cols))
print("Числовых:", len(num_cols))

"""## Шаг 3. Разделение на train/test и предобработка

- Делим данные на обучающую и тестовую выборки (80/20).  
- Категориальные признаки переводим в числа с помощью `OrdinalEncoder`.  
- Все признаки масштабируем через `StandardScaler`, чтобы сеть обучалась стабильнее.

"""

# Train/Test split
X_train_df, X_test_df, y_train, y_test = train_test_split(
    X_df, y, test_size=0.2, random_state=RANDOM_STATE
)

# OrdinalEncoder для категориальных
enc = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
X_train_cat = enc.fit_transform(X_train_df[cat_cols]) if len(cat_cols) else np.zeros((len(X_train_df), 0))
X_test_cat  = enc.transform(X_test_df[cat_cols])      if len(cat_cols) else np.zeros((len(X_test_df), 0))

# Числовые признаки
X_train_num = X_train_df[num_cols].astype(np.float32).values if len(num_cols) else np.zeros((len(X_train_df), 0), dtype=np.float32)
X_test_num  = X_test_df[num_cols].astype(np.float32).values  if len(num_cols) else np.zeros((len(X_test_df), 0), dtype=np.float32)

# Объединяем
X_train_raw = np.hstack([X_train_num, X_train_cat]).astype(np.float32)
X_test_raw  = np.hstack([X_test_num,  X_test_cat ]).astype(np.float32)

# StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train_raw)
X_test  = scaler.transform(X_test_raw)

print("\n✅ Готово:")
print("X_train:", X_train.shape, "| X_test:", X_test.shape)

"""## Шаг 4. Архитектура нейросети

Строим полносвязную нейросеть (FCN) для регрессии:

- несколько слоёв `Dense` с активацией ReLU;
- `BatchNormalization` и `Dropout` для стабильности и против переобучения;
- L2‑регуляризация весов;
- оптимизатор Adam, loss = MSE, метрика = MAE.

"""

# Модель FCN (регрессия)
def build_model(input_dim: int) -> keras.Model:
    l2 = regularizers.l2(1e-4)
    m = models.Sequential([
        layers.Input(shape=(input_dim,)),

        layers.Dense(64, activation="relu", kernel_regularizer=l2),
        layers.BatchNormalization(),
        layers.Dropout(0.20),

        layers.Dense(32, activation="relu", kernel_regularizer=l2),
        layers.BatchNormalization(),
        layers.Dropout(0.20),

        layers.Dense(16, activation="relu", kernel_regularizer=l2),
        layers.Dropout(0.10),

        layers.Dense(1, activation="linear")
    ])
    m.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss="mse",
        metrics=["mae"]
    )
    return m

model = build_model(X_train.shape[1])
model.summary()

"""## Шаг 5. Обучение модели

Используем две техники:

- **EarlyStopping** – останавливает обучение, если качество на валидации перестаёт улучшаться.  
- **ReduceLROnPlateau** – уменьшает шаг обучения, когда val‑loss выходит на плато.

Это помогает получить плавные, сходящиеся кривые без переобучения.

"""

early_stop = callbacks.EarlyStopping(
    monitor="val_loss", patience=25, restore_best_weights=True, verbose=1
)
reduce_lr = callbacks.ReduceLROnPlateau(
    monitor="val_loss", factor=0.5, patience=10, min_lr=1e-5, verbose=1
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

"""## Шаг 6. Качество модели на тестовой выборке

Здесь считаем итоговые метрики на отложенной выборке:
- MAE – средняя абсолютная ошибка;
- RMSE – корень из среднеквадратичной ошибки;
- R² – доля объяснённой дисперсии (насколько хорошо модель объясняет вариацию целевой переменной).

"""

pred_test = model.predict(X_test, verbose=0).flatten()

mae = mean_absolute_error(y_test, pred_test)
rmse = np.sqrt(mean_squared_error(y_test, pred_test))
r2 = r2_score(y_test, pred_test)

print("\n📊 TEST метрики (регрессия):")
print(f"MAE:  {mae:.3f}")
print(f"RMSE: {rmse:.3f}")
print(f"R²:   {r2:.4f}")

"""## Шаг 7. Графики истории обучения

На этих графиках видно, как в процессе обучения:

- MAE на обучении и валидации постепенно уменьшается и кривые идут рядом;
- MSE (loss) на обучении и валидации тоже плавно убывает и не расходится.

Это говорит о том, что модель обучается нормально и не переобучается.

"""

epochs = range(1, len(history.history["loss"]) + 1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(epochs, history.history["mae"], label="Обучающая MAE", linewidth=2)
axes[0].plot(epochs, history.history["val_mae"], label="Валидационная MAE", linewidth=2)
axes[0].set_title("MAE обучения и валидации")
axes[0].set_xlabel("Эпоха")
axes[0].set_ylabel("MAE")
axes[0].grid(True, alpha=0.3)
axes[0].legend()

axes[1].plot(epochs, history.history["loss"], label="Обучающая функция потерь", linewidth=2)
axes[1].plot(epochs, history.history["val_loss"], label="Валидационная функция потерь", linewidth=2)
axes[1].set_title("Функция потерь обучения и валидации")
axes[1].set_xlabel("Эпоха")
axes[1].set_ylabel("MSE Loss")
axes[1].grid(True, alpha=0.3)
axes[1].legend()

plt.tight_layout()
plt.show()

"""## Шаг 8. Демонстрация работы НС (HTML-страница)

Ниже запускается простое HTML-приложение (Gradio) с формой ввода признаков.
Модель возвращает прогноз суммы покупки (USD).

"""

# --- HTML-приложение в Colab через Gradio: сумма + уровень способности ---
!pip -q install gradio

import gradio as gr
import numpy as np
import pandas as pd

# ВАЖНО: запускать ПОСЛЕ обучения, чтобы существовали:
# model, enc, scaler, cat_cols, num_cols, df

# -------------------------
# 1) Русские подписи полей
# -------------------------
RU_LABELS = {
    "Age": "Возраст",
    "Gender": "Пол",
    "Category": "Категория товара",
    "Item Purchased": "Купленный товар",
    "Size": "Размер",
    "Color": "Цвет",
    "Season": "Сезон",
    "Location": "Локация/город",

    "Payment Method": "Способ оплаты",
    "Shipping Type": "Тип доставки",
    "Preferred Payment Method": "Предпочитаемый способ оплаты",

    "Subscription Status": "Подписка (да/нет)",
    "Discount Applied": "Скидка применена",
    "Promo Code Used": "Промокод использован",

    "Previous Purchases": "Предыдущие покупки (кол-во)",
    "Review Rating": "Оценка (рейтинг)",
    "Frequency of Purchases": "Частота покупок",
}

def ru_label(col_name: str) -> str:
    return RU_LABELS.get(col_name, col_name)

# -------------------------
# 2) Перевод значений (только для простых Yes/No и пола)
# -------------------------
RU_VALUES = {
    "Gender": {"Male": "Мужской", "Female": "Женский"},
    "Subscription Status": {"Yes": "Да", "No": "Нет"},
    "Discount Applied": {"Yes": "Да", "No": "Нет"},
    "Promo Code Used": {"Yes": "Да", "No": "Нет"},
}

def to_ru_value(col, val):
    return RU_VALUES.get(col, {}).get(val, val)

def to_en_value(col, val_ru):
    rev = {v: k for k, v in RU_VALUES.get(col, {}).items()}
    return rev.get(val_ru, val_ru)

# -------------------------
# 3) Пороги уровней покупательской способности (по датасету)
# -------------------------
target_col = "Purchase Amount (USD)"
q1 = float(df[target_col].quantile(0.25))
q3 = float(df[target_col].quantile(0.75))

def ability_level(pred_usd: float) -> str:
    if pred_usd < q1:
        return f"Низкая покупательская способность (ниже Q1 = ${q1:.2f})"
    elif pred_usd < q3:
        return f"Средняя покупательская способность (между Q1=${q1:.2f} и Q3=${q3:.2f})"
    else:
        return f"Высокая покупательская способность (выше Q3 = ${q3:.2f})"

print(f"✅ Пороги уровней: Q1=${q1:.2f}, Q3=${q3:.2f}")

# -------------------------
# 4) Списки для формы
# -------------------------
cat_choices_raw = {}
for c in cat_cols:
    cat_choices_raw[c] = sorted(df[c].dropna().astype(str).unique().tolist())

num_defaults = {}
for c in num_cols:
    num_defaults[c] = float(pd.to_numeric(df[c], errors="coerce").dropna().mean())

# -------------------------
# 5) Предсказание: сумма + уровень
# -------------------------
def predict_purchase_amount_and_level(*inputs):
    data = {}
    idx = 0

    # Числовые
    for c in num_cols:
        data[c] = [float(inputs[idx])]
        idx += 1

    # Категориальные
    for c in cat_cols:
        val_ru = str(inputs[idx])
        data[c] = [to_en_value(c, val_ru)]
        idx += 1

    row = pd.DataFrame(data)

    # Препроцессинг как в обучении
    X_cat = enc.transform(row[cat_cols]) if len(cat_cols) else np.zeros((1, 0), dtype=np.float32)
    X_num = row[num_cols].astype(np.float32).values if len(num_cols) else np.zeros((1, 0), dtype=np.float32)

    X_raw = np.hstack([X_num, X_cat]).astype(np.float32)
    X_scaled = scaler.transform(X_raw)

    pred = float(model.predict(X_scaled, verbose=0).flatten()[0])
    pred_round = float(round(pred, 2))

    level = ability_level(pred_round)
    return pred_round, level

# -------------------------
# 6) UI
# -------------------------
inputs_ui = []

for c in num_cols:
    inputs_ui.append(gr.Number(label=ru_label(c), value=num_defaults.get(c, 0.0)))

for c in cat_cols:
    raw = cat_choices_raw[c]
    ru_list = [to_ru_value(c, v) for v in raw]
    default = ru_list[0] if len(ru_list) else ""
    inputs_ui.append(gr.Dropdown(choices=ru_list, value=default, label=ru_label(c)))

demo = gr.Interface(
    fn=predict_purchase_amount_and_level,
    inputs=inputs_ui,
    outputs=[
        gr.Number(label="Прогноз суммы покупки (USD)"),
        gr.Textbox(label="Оценка покупательской способности", lines=2)
    ],
    title="Прогноз покупательской способности (FCN / TensorFlow)",
    description="Модель прогнозирует сумму покупки (USD) и переводит её в уровень покупательской способности по квартилям датасета (Q1/Q3)."
)

demo.launch(share=True)